scalar Date
scalar Json

enum Publisher {
  COLUMBIA_UNIVERSITY_PRESS
  NANJING_UNIVERSITY_PRESS
  XXX_PRESS
}

type Book {
  id: ID!
  title: String!
  publisher: Publisher!
  author: Person!
  meta: Json
  published_at: Date!
}

type Person {
  id: ID!
  name: String!
  books(title_like: String, publisher: Publisher): [Book!]!
}

type Query {
  books(author_id: ID, title_like: String, publisher: Publisher): [Book!]!
  persons(name_like: String): [Person!]!
}

type Mutation {
  add_person(name: String!): Person!
  add_book(title: String!, publisher: Publisher!, author_id: ID!, published_at: Date!, meta: Json): Book!
}

schema {
  query: Query
  mutation: Mutation
}
